@echo off
echo Starting SAP Explorer...
echo.
echo Starting backend...
start /B cmd /c "cd backend && npm run dev"
echo Starting frontend...
start /B cmd /c "cd frontend && npm run dev"
echo.
echo Waiting for applications to start...
timeout /t 5 /nobreak >nul
echo.
echo Opening browser...
start http://localhost:5173
pause
exit